package july.july26

val listOfAnimals = listOf(
    "Aardvark",
    "Aardwolf",
    "African Elephant",
    "African Grey Parrot",
    "Albatross",
    "Alligator",
    "Alpaca",
    "American Bison",
    "American Robin",
    "Anaconda",
    "Angelfish",
    "Ant",
    "Anteater",
    "Antelope",
    "Ape",
    "Arctic Fox",
    "Arctic Hare",
    "Armadillo",
    "Asian Elephant",
    "Asiatic Black Bear",
    "Axolotl",
    "Baboon",
    "Badger",
    "Bandicoot",
    "Barn Owl",
    "Barracuda",
    "Barramundi",
    "Bat",
    "Beagle",
    "Bear",
    "Beaver",
    "Bee",
    "Beetle",
    "Beluga Whale",
    "Bengal Tiger",
    "Binturong",
    "Bird of Paradise",
    "Bison",
    "Black Marlin",
    "Black Widow Spider",
    "Blobfish",
    "Blue Jay",
    "Blue Whale",
    "Boa Constrictor",
    "Bobcat",
    "Bonobo",
    "Booby",
    "Border Collie",
    "Bottlenose Dolphin",
    "Bowerbird",
    "Box Jellyfish",
    "Boxer Dog",
    "Brachiosaurus",
    "Brown Bear",
    "Bumblebee",
    "Butterfly",
    "Camel",
    "Capybara",
    "Caracal",
    "Cardinal",
    "Caribou",
    "Cassowary",
    "Cat",
    "Caterpillar",
    "Catfish",
    "Cheetah",
    "Chicken",
    "Chimpanzee",
    "Chinchilla",
    "Chipmunk",
    "Clam",
    "Clownfish",
    "Cobra",
    "Cockatoo",
    "Cockroach",
    "Cod",
    "Coelacanth",
    "Collie",
    "Common Loon",
    "Coral",
    "Cormorant",
    "Cougar",
    "Cow",
    "Coyote",
    "Crab",
    "Crane",
    "Crawfish",
    "Crocodile",
    "Crow",
    "Cuckoo",
    "Curlew",
    "Cuttlefish",
    "Dalmatian",
    "Damselfish",
    "Deer",
    "Dingo",
    "Dodo",
    "Dog",
    "Dolphin",
    "Donkey",
    "Dory",
    "Dove",
    "Dragonfly",
    "Dugong",
    "Dung Beetle",
    "Eagle",
    "Earthworm",
    "Echidna",
    "Eel",
    "Egret",
    "Elephant",
    "Elephant Seal",
    "Elk",
    "Emu",
    "Falcon",
    "Ferret",
    "Finch",
    "Firefly",
    "Fish",
    "Flamingo",
    "Flounder",
    "Fly",
    "Flying Squirrel",
    "Fossa",
    "Fox",
    "Frigatebird",
    "Frog",
    "Fruit Bat",
    "Galapagos Penguin",
    "Galapagos Tortoise",
    "Gazelle",
    "Gecko",
    "Gerbil",
    "Gibbon",
    "Giraffe",
    "Goat",
    "Goldfish",
    "Goose",
    "Gopher",
    "Gorilla",
    "Grasshopper",
    "Great White Shark",
    "Green Turtle",
    "Greyhound",
    "Grizzly Bear",
    "Grouse",
    "Guinea Fowl",
    "Guinea Pig",
    "Gull",
    "Hammerhead Shark",
    "Hamster",
    "Hare",
    "Harp Seal",
    "Harpy Eagle",
    "Hawk",
    "Hedgehog",
    "Heron",
    "Herring",
    "Hippopotamus",
    "Honeybee",
    "Hornbill",
    "Hornet",
    "Horse",
    "Hummingbird",
    "Humpback Whale",
    "Hyena",
    "Ibex",
    "Ibis",
    "Iguana",
    "Impala",
    "Indian Elephant",
    "Indian Rhinoceros",
    "Indigo Bunting",
    "Insect",
    "Jackal",
    "Jackrabbit",
    "Jaguar",
    "Javan Rhino",
    "Jellyfish",
    "Kestrel",
    "Kingfisher",
    "Kiwi",
    "Koala",
    "Komodo Dragon",
    "Kookaburra",
    "Krill",
    "Ladybug",
    "Lamprey",
    "Land Snail",
    "Lanternfish",
    "Lark",
    "Leafcutter Ant",
    "Lemur",
    "Leopard",
    "Leopard Seal",
    "Liger",
    "Lion",
    "Lionfish",
    "Little Penguin",
    "Lizard",
    "Llama",
    "Lobster",
    "Locust",
    "Loggerhead Turtle",
    "Long-Eared Owl",
    "Longhorn Beetle",
    "Lorikeet",
    "Louse",
    "Lynx",
    "Macaw",
    "Magpie",
    "Mallard",
    "Mamba",
    "Manatee",
    "Mandrill",
    "Manta Ray",
    "Marine Iguana",
    "Markhor",
    "Marmoset",
    "Marmot",
    "Marsupial Mole",
    "Meerkat",
    "Millipede",
    "Mink",
    "Mole",
    "Mongoose",
    "Mongrel",
    "Monitor Lizard",
    "Monkey",
    "Moose",
    "Moray Eel",
    "Moth",
    "Mountain Goat",
    "Mouse",
    "Mule",
    "Narwhal",
    "Nautilus",
    "New Guinea Singing Dog",
    "Newt",
    "Nighthawk",
    "Numbat",
    "Ocelot",
    "Octopus",
    "Okapi",
    "Olm",
    "Opossum",
    "Orangutan",
    "Orca",
    "Ostrich",
    "Otter",
    "Owl",
    "Ox",
    "Oyster",
    "Painted Turtle",
    "Panther",
    "Parrot",
    "Partridge",
    "Peacock",
    "Pelican",
    "Penguin",
    "Perch",
    "Peregrine Falcon",
    "Pheasant",
    "Pigeon",
    "Pig",
    "Pike",
    "Piranha",
    "Platypus",
    "Polar Bear",
    "Pony",
    "Porcupine",
    "Porpoise",
    "Possum",
    "Prairie Dog",
    "Puffin",
    "Puma",
    "Python",
    "Quail",
    "Quokka",
    "Quoll",
    "Rabbit",
    "Raccoon",
    "Rainbow Fish",
    "Rat",
    "Rattlesnake",
    "Raven",
    "Red Deer",
    "Red Fox",
    "Red Panda",
    "Reindeer",
    "Rhinoceros",
    "Robin",
    "Rock Hyrax",
    "Rooster",
    "Salamander",
    "Salmon",
    "Sand Dollar",
    "Sandpiper",
    "Saola",
    "Sardine",
    "Scallop",
    "Scorpion",
    "Seahorse",
    "Seal",
    "Serval",
    "Shark",
    "Sheep",
    "Shrew",
    "Shrimp",
    "Siamang",
    "Siberian Tiger",
    "Skink",
    "Skunk",
    "Sloth",
    "Snail",
    "Snake",
    "Snow Leopard",
    "Snowy Owl",
    "Solenodon",
    "Sparrow",
    "Spider",
    "Sponge",
    "Squid",
    "Squirrel",
    "Starfish",
    "Star-nosed Mole",
    "Steller's Sea Cow",
    "Stingray",
    "Stoat",
    "Stork",
    "Sun Bear",
    "Swallow",
    "Swan",
    "Tamarin",
    "Tanager",
    "Tapir",
    "Tarsier",
    "Tasmanian Devil",
    "Termite",
    "Tern",
    "Thylacine",
    "Tiger",
    "Tiger Shark",
    "Toad",
    "Tortoise",
    "Toucan",
    "Tree Frog",
    "Trout",
    "Tuna",
    "Turkey",
    "Turritopsis Dohrnii (Immortal Jellyfish)",
    "Turtle",
    "Viper",
    "Vulture",
    "Wallaby",
    "Walrus",
    "Warthog",
    "Wasp",
    "Water Buffalo",
    "Weasel",
    "Whale",
    "White Rhinoceros",
    "Whooping Crane",
    "Wildebeest",
    "Wolf",
    "Wolverine",
    "Wombat",
    "Woodpecker",
    "Worm",
    "Wrasse",
    "Wren",
    "Yak",
    "Yellowfin Tuna",
    "Yellowjacket",
    "Zebra",
    "Zebu",
    "Zokor",
    "Zonkey",
    "Zorse",
)